---
- hosts: util
  become: true
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: latest

    - name: Install nginx
      yum:
        name: nginx
        state: latest

    - name: Starts nginx
      service:
        name: nginx
        state: started

    - name: Add firewall rule for port 80
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
    
    - name: Reloads the firewall
      command: firewall-cmd --reload
    
