---
- hosts: util
  become: true
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: latest

    - name: Install nginx
    yum:
      name: nginx
      state: latest

    - name: Start nginx
      service:
        name: nginx
        state: started

    - name: Add firewall rule for port 80
      firewalld:
        port: 80
        permanent: yes
        state: enabled
    
    - name: Reload firewall
      command: firewall-cmd --reload
    
